_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 4ccc36ba-019f-47dc-8854-cccee660224b
name: 'Semantic UI with daisyUI Components'
mail: lisa@codementality.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
